# Generated by Django 4.1.1 on 2022-10-03 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_watchlist_listing_id_remove_watchlist_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='listing_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
