# Generated by Django 4.1.1 on 2022-10-06 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_watchlist_listing_id_alter_watchlist_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listing_id',
        ),
        migrations.AlterField(
            model_name='bids',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bids',
            name='listing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
