# Generated by Django 4.1.1 on 2022-10-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_rename_user_id_comments_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='user',
            new_name='user_id',
        ),
    ]
