# Generated by Django 4.1.1 on 2022-10-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_rename_listing_bids_listing_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='user_id',
            new_name='user',
        ),
    ]
