# Generated by Django 4.1.1 on 2022-10-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='./static/auctions/images/user.png', null=True),
        ),
    ]
