# Generated by Django 4.1.1 on 2022-10-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
